version: "3.8"

services:
  mongo: 
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
    - "27018:27017"
    volumes:
      - mongo-data:/data/db

  admin:
    image: admin:latest
    container_name: admin
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  frontend:
    image: frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - backend
      
  backend:
    image: backend:latest
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGODB_URL: "mongodb://mongo:27017/food_frenzy"  

volumes:
  mongo-data: 
