apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: princekansagra/food_frnezy:backendmain
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGODB_URL

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
  type: NodePort

