apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-claim
spec:
  volumeName: host
  storageClassName: standard
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi