apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
          
---

apiVersion: v1
kind: Service
metadata:
  name: service-mongo
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
